# whitelist

langauge: java

env:
    TRAVIS_BUILD_DIR=repository/target/products/

sudo: false

dist: trusty

addons:
  apt:
    packages:
      - oracle-java8-installer
jdk:
  - oraclejdk8

install: echo 'Skipping mvn install'

before_script:
 - chmod +x build/travis.sh
 - echo "MAVEN_OPTS='-Xmx2g -Xms1g'" > ~/.mavenrc

script:
 - java -version
 - ./build/travis.sh

after_failure:
 - find ./ -type d -name "surefire-reports" -print0 | xargs -0 -I {} find {} -iname "*.txt" -type f | xargs cat

deploy:
    provider: releases
    api_key:  "GITHUB OAUTH TOKEN"
    file:
        - cs-studio-jlab-4.5.0-linux.gtk.x86_64.tar.gz
        - cs-studio-jlab-4.5.0-linux.gtk.x86.tar.gz
        - cs-studio-jlab-4.5.0-macosx.cocoa.x86_64.zip
        - cs-studio-jlab-4.5.0-win32.win32.x86_64.zip
    skip_cleanup: true
    on:
        tags: true
